import { IAutocompleteOption } from "@/components/ui/autocomplete";

// temp: this should not be in frontend. this will be changed soon.
export const DEGREES: IAutocompleteOption<string>[] = [
  "Accountancy",
  "Accounting Information Systems",
  "Accounting Technology",
  "Agribusiness",
  "Agricultural and Biosystems Engineering",
  "Agriculture",
  "Agroforestry",
  "Aircraft Maintenance Technology",
  "Animal Science",
  "Anthropology",
  "Applied Mathematics",
  "Applied Physics",
  "Applied Statistics",
  "Architecture",
  "Biochemistry",
  "Biology",
  "Business Administration",
  "Business Analytics",
  "Business Management",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Communications",
  "Community Development",
  "Computer Engineering",
  "Computer Science",
  "Creative Writing",
  "Criminology",
  "Culinary Arts",
  "Customs Administration",
  "Cybersecurity",
  "Data Science and Analytics",
  "Dental Medicine",
  "Development Communication",
  "Disaster Risk Management",
  "Early Childhood Education",
  "Economics",
  "Electrical Engineering",
  "Electronics Engineering",
  "Elementary Education",
  "Entrepreneurship",
  "Environmental Engineering",
  "Environmental Planning",
  "Environmental Science",
  "Fashion Design",
  "Film",
  "Finance",
  "Fine Arts",
  "Fisheries",
  "Food Engineering",
  "Food Technology",
  "Forestry",
  "Game Development and Animation",
  "Geodetic Engineering",
  "Geology",
  "History",
  "Horticulture",
  "Hospitality Management",
  "Hotel and Restaurant Management",
  "Human Resource Management",
  "Human Services",
  "Industrial Design",
  "Industrial Engineering",
  "Information Systems",
  "Information Technology",
  "Interior Design",
  "International Studies",
  "Journalism",
  "Landscape Architecture",
  "Law",
  "Library and Information Science",
  "Management Accounting",
  "Manufacturing Engineering",
  "Marine Biology",
  "Marine Engineering",
  "Marketing",
  "Materials Engineering",
  "Mathematics",
  "Mechanical Engineering",
  "Mechatronics Engineering",
  "Medical Laboratory Science",
  "Medical Technology",
  "Midwifery",
  "Mining Engineering",
  "Multimedia Arts",
  "Music",
  "Naval Architecture and Marine Engineering",
  "Nursing",
  "Nutrition and Dietetics",
  "Occupational Therapy",
  "Operations Management",
  "Optometry",
  "Peace Studies",
  "Petroleum Engineering",
  "Pharmacy",
  "Philosophy",
  "Physical Education",
  "Physical Therapy",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Administration",
  "Public Health",
  "Public Management",
  "Radiologic Technology",
  "Real Estate Management",
  "Renewable Energy",
  "Robotics Engineering",
  "Secondary Education",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Special Needs Education",
  "Speech and Language Pathology",
  "Sports and Exercise Science",
  "Statistics",
  "Supply Chain Management",
  "Technology and Livelihood Education",
  "Theater Arts",
  "Tourism Management",
  "Veterinary Medicine",
  "Other",
].map((degree) => ({
  id: degree,
  name: degree,
}));
