name: Notify Discord on Vercel Deploy

on:
  deployment_status:

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord of success (DEV)
        if: github.event.deployment_status.state == 'success' && github.event.deployment.ref == 'refs/heads/develop'
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"✅ [DEV] Deployment *${{ github.event.deployment_status.environment }}* succeeded for commit [${{ github.sha }}](${{ github.event.repository.html_url }}/commit/${{ github.sha }})\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord of failure (DEV)
        if: github.event.deployment_status.state == 'failure' && github.event.deployment.ref == 'refs/heads/develop'
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"❌ [DEV] Deployment *${{ github.event.deployment_status.environment }}* FAILED for commit [${{ github.sha }}](${{ github.event.repository.html_url }}/commit/${{ github.sha }})\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
