# This is meant to run on the deployment fork

name: Sync Deployment Fork with Upstream

on:
  workflow_dispatch:     # Allows manual trigger

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Notify Discord of Initiation
        run: |
          curl -H "Content-Type: application/json" -d '{"content":"# Prod\n Initiating Deployment..."}' ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/BetterInternship/Client.git
          git fetch upstream
          git reset --hard upstream/main

      - name: Push changes to fork
        run: |
          git push origin main --force

      - name: Deploy to Vercel
        id: vercel
        run: |
          URL=$(npx vercel --prod --token="${{ secrets.VERCEL_TOKEN }}" --name=better-internship-client --confirm)
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Notify Discord of Success
        if: ${{ success() }}
        run: |
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          curl -H "Content-Type: application/json" -d '{"content":"# Prod\n✅ Deployment Success\n[${{ github.sha::0:7 }}](${COMMIT_URL})\nhttps://betterinternship.com"}' ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Discord of Failure
        if: ${{ failure() }}
        run: |
          curl -H "Content-Type: application/json" -d '{"content":"# Prod\n❌ Deployment failed\ncommit [${{ github.sha::0:7 }}](${COMMIT_URL})\n@BetterInternship"}' ${{ secrets.DISCORD_WEBHOOK_URL }}
